version: '3.7'

services:
    nginx:
        image: nginx:1.17.4
        container_name: task_nginx
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./docker_settings/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker_settings/logs:/var/log/nginx
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - app-network

    php:
        build:
            context: ./docker_settings
            dockerfile: Dockerfile_php81
        container_name: task_php
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker_settings/php.ini:/usr/local/etc/php/conf.d/php-memory-limit.ini
        depends_on:
            - mysql82
        networks:
            - app-network

    mysql82:
        build:
            context: ./docker_settings
            dockerfile: ./Dockerfile_mysql82
        container_name: task_mysql82
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: Europe/Budapest
            LANG: C.UTF_8
            MYSQL_CHARSET: utf8mb4
            MYSQL_COLLATION: utf8mb4_unicode_ci
        ports:
            - "33064:3306"
        volumes:
            - ./docker_settings/mysql82_data:/var/lib/mysql
        user: ${CURRENT_UID:-}
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        container_name: task_phpmyadmin
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_HOST: mysql82
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 1000M
        depends_on:
            - mysql82
        networks:
            - app-network

    node:
        build:
            context: .
            dockerfile: docker_settings/Dockerfile_node
        container_name: task_node
        volumes:
            - './:/www/local'
        restart: always
        ports:
            - 8085:8080
        working_dir: /www/local
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
    web:
        external: true

volumes:
    mysql_data:
        driver: local
